// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGkAjm9KkrxfUcbciskO900rlg3emrY2E',
    appId: '1:775809081802:web:3cd9fcf7e975f6d00aaf33',
    messagingSenderId: '775809081802',
    projectId: 'lms-education-fd311',
    authDomain: 'lms-education-fd311.firebaseapp.com',
    storageBucket: 'lms-education-fd311.firebasestorage.app',
    measurementId: 'G-X3CX4XF2N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0HDTLB7r5C3OFyCBD9TQZbk56ec1Jk5Y',
    appId: '1:775809081802:android:6d3ecb10b220af380aaf33',
    messagingSenderId: '775809081802',
    projectId: 'lms-education-fd311',
    storageBucket: 'lms-education-fd311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC55DcvMkSa9Kmtb2TQk3AsrraqdLEJ1Lg',
    appId: '1:775809081802:ios:04fd207bd1c66a050aaf33',
    messagingSenderId: '775809081802',
    projectId: 'lms-education-fd311',
    storageBucket: 'lms-education-fd311.firebasestorage.app',
    iosBundleId: 'com.example.lms',
  );
}
